added matplotlib to installation

diff --git a/install_dependencies b/install_dependencies
--- a/install_dependencies
+++ b/install_dependencies
@@ -12,6 +12,7 @@ repo_dir=`pwd`
 
 is_installed_python_smbus=False
 is_installed_python_opencv=False
+is_installed_python_matplotlib=False
 
 if [ "$(whoami)" != "root" ] ; then
     echo -e "You must run this script as root."
@@ -56,10 +57,16 @@ function print_result(){
     else
         echo -e "Failed"
     fi
+    echo -e "python-matplotlib  \c"
+    if $is_installed_python_matplotlib; then
+        echo -e "Success"
+    else
+        echo -e "Failed"
+    fi
 }
 
 ###################################
-# install python-pip python-smbus python-opencv runtime #
+# install python-pip python-smbus python-opencv python-matplotlib runtime #
 ###################################
 echo -e "\nInstalling python3-smbus and git\n"
 if sudo apt-get install python3-smbus git -y; then
@@ -90,6 +97,23 @@ else
         end
     fi
 fi
+
+echo -e "\nInstalling python3-matplotlib \n"
+if sudo apt-get install python3-matplotlib -y; then
+    echo -e "    Successfully installed python-opencv \n"
+    is_installed_python_opencv=true
+else
+    echo -e "    Failed to installed python-opencv \n"
+    echo -e "    Do you want to skip this? \c"
+    if_continue
+    if [ $? = 1 ] ; then
+        echo -e "    Skipped python-opencv installation."
+    else
+        end
+    fi
+fi
+
+##########################################################
 
 print_result
 
